

var processing_data = [
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "이비인후과",
    "address": "신촌로 92 신촌카리스빌딩 2,3층 (노고산동)",
    "name": "김성전·김시찬이비인후과의원",
    "category": "의원",
    "tel": "02-324-9127",
    "zipcode": "04058",
    "homepage": "",
    "weekday": "09:00 ~ 19:00",
    "saturday": "09:00 ~ 13:00",
    "holiday": "08:00~ 10:00",
    "remarks": "",
    "photo": "",
    "review": "진료를 세심히 봐주지만 대기 시간이 조금 길다. 간호사가 친절하다"
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "이비인후과",
    "address": "신촌로 88 5층 (노고산동, 태영빌딩)",
    "name": "신촌연세이비인후과의원",
    "category": "의원",
    "tel": "02-332-0927",
    "zipcode": "04058",
    "homepage": "http://www.yonseient.co.kr/",
    "weekday": "10:00 ~ 17:30",
    "saturday": "10:00 ~ 13:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "노고산동_신촌연세이비인후과의원_01.jpg,노고산동_신촌연세이비인후과의원_02.jpg",
    "review": "의사 선생님께서 굉장히 자세히 설명해주신다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "내과,소아청소년과,이비인후과,재활의학과",
    "address": "신촌로 68 4,5층 (노고산동)",
    "name": "연세우리내과의원",
    "category": "의원",
    "tel": "02-334-7560",
    "zipcode": "04057",
    "homepage": "",
    "weekday": "08:30 ~ 18:30",
    "saturday": "08:30 ~ 16:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00",
    "photo": "노고산동_연세우리내과의원_01.jpg,노고산동_연세우리내과의원_02.jpg",
    "review": "대기시간이 다른곳 보다 길지만 시설이 아주 깔끔하고 청결하다"
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "이비인후과",
    "address": "연세로 3-3 (창천동)",
    "name": "신촌이비인후과의원",
    "category": "의원",
    "tel": "02-324-1329",
    "zipcode": "03789",
    "homepage": "",
    "weekday": "10:00 ~ 17:30",
    "saturday": "10:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "",
    "review": "의사선생님이 연세가 많으시나 꼼꼼하고 친절하다. 환자의 건강을 생각한다"
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "이비인후과",
    "address": "신촌로 23 (창천동)",
    "name": "위풍환이비인후과의원",
    "category": "의원",
    "tel": "02-324-2741",
    "zipcode": "03785",
    "homepage": "",
    "weekday": "09:30 ~ 18:00",
    "saturday": "09:30 ~ 14:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "",
    "review": "장비는 조금 오래되었지만 실력이 좋다고 소문이 나있다고 한다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "내과,소아청소년과,이비인후과",
    "address": "신촌로 78 2층 (노고산동)",
    "name": "연세김진민의원",
    "category": "의원",
    "tel": "02-718-0131",
    "zipcode": "04057",
    "homepage": "",
    "weekday": "09:00 ~ 17:30",
    "saturday": "09:00 ~ 12:00",
    "holiday": "휴무",
    "remarks": "토요일 첫주 휴진",
    "photo": "노고산동_연세김진민의원_01.jpg,노고산동_연세김진민의원_02.jpg",
    "review": "검증된 곳으로 알려져있다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "내과",
    "address": "서강로 133 4층 (노고산동, 병우빌딩)",
    "name": "연세이현철내과의원",
    "category": "의원",
    "tel": "02-337-7570",
    "zipcode": "04058",
    "homepage": "http://endolee.com/",
    "weekday": "08:30 ~ 17:30",
    "saturday": "09:00 ~ 13:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "노고산동_연세이현철내과의원_01.jpg,노고산동_연세이현철내과의원_02.jpg",
    "review": "의사의 경력이 뛰어나고, 명성있는 교수다. 시설이 깔끔하다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "내과,가정의학과",
    "address": "신촌로 120 2, 3층 (노고산동)",
    "name": "허내과의원",
    "category": "의원",
    "tel": "02-718-1827",
    "zipcode": "04101",
    "homepage": "",
    "weekday": "09:00 ~ 17:00",
    "saturday": "휴무",
    "holiday": "휴무",
    "remarks": "점심시간 12:00 ~ 14:00",
    "photo": "",
    "review": "의사는 친절하나 직원이 불친절하다"
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "내과",
    "address": "신촌로 13 3층 (창천동, 아륭빌딩)",
    "name": "독일의원",
    "category": "의원",
    "tel": "02-334-1008",
    "zipcode": "03785",
    "homepage": "http://www.dokilheart.co.kr/",
    "weekday": "09:00 ~ 18:00",
    "saturday": "09:00 ~ 13:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00",
    "photo": "",
    "review": "대기시간이 아주 길다. 하지만, 의사와 간호사들이 친절하다"
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "치과",
    "address": "신촌로 73 케이스퀘어 7층 (창천동)",
    "name": "리얼라인치과의원",
    "category": "치과의원",
    "tel": "02-553-7528",
    "zipcode": "03789",
    "homepage": "http://real-line.co.kr/",
    "weekday": "10:00 ~ 21:00",
    "saturday": "10:00 ~ 15:00",
    "holiday": "휴무",
    "remarks": "수요일 금요일 10:00 ~ 19:00",
    "photo": "창천동_리얼라인치과의원_01.jpg,창천동_리얼라인치과의원_02.jpg,창천동_리얼라인치과의원_03.jpg",
    "review": "진료를 잘하고 저렴하다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "치과",
    "address": "신촌로 61 6층 (창천동)",
    "name": "서울바른이치과교정과치과의원",
    "category": "치과의원",
    "tel": "02-325-2810",
    "zipcode": "03787",
    "homepage": "http://www.barunee.co.kr/",
    "weekday": "10:00 ~ 18:30",
    "saturday": "09:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "목요일 휴무",
    "photo": "창천동_서울바른이치과교정과치과의원_01.jpg,창천동_서울바른이치과교정과치과의원_02.jpg,창천동_서울바른이치과교정과치과의원_03.jpg",
    "review": "교정을 전문으로 하고 잘한다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "치과",
    "address": "신촌로 67 5층 (창천동)",
    "name": "연세해맑은치과의원",
    "category": "치과의원",
    "tel": "02-3143-2275",
    "zipcode": "03787",
    "homepage": "http://www.beautifulsmile.co.kr/",
    "weekday": "10:00 ~ 19:00",
    "saturday": "09:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "수요일 10:00 ~ 21:00 목요일 휴무",
    "photo": "창천동_연세해맑은치과의원_01.jpg,창천동_연세해맑은치과의원_02.jpg,창천동_연세해맑은치과의원_03.jpg",
    "review": "불필요한 치료를 권하지 않고 친절하다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "치과",
    "address": "연세로5길 26 5,7,9층 (창천동)",
    "name": "잎사귀치과병원",
    "category": "치과병원",
    "tel": "02-3141-4947",
    "zipcode": "03789",
    "homepage": "http://www.5ok.co.kr/",
    "weekday": "09:30 ~ 20:00",
    "saturday": "09:30 ~ 14:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "창천동_잎사귀치과의원_01.jpg,창천동_잎사귀치과의원_02.jpg,창천동_잎사귀치과의원_03.jpg",
    "review": "시설이 좋고 실력이 좋다. 전화를 잘 안받는다. 사랑니 발치에 우수한 실력을 지니고 있다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "치과",
    "address": "연세로 39 2층 (창천동)",
    "name": "장병량치과의원",
    "category": "치과의원",
    "tel": "02-323-0363",
    "zipcode": "03788",
    "homepage": "",
    "weekday": "10:00 ~ 18:30",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00",
    "photo": "",
    "review": "의사선생님이 유머가 있고 과잉진료를 하지 않는다. 간호사가 친절하다"
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "안과",
    "address": "백범로 3 2,3,4층 (노고산동)",
    "name": "신촌연세안과의원",
    "category": "의원",
    "tel": "02-716-8275",
    "zipcode": "04101",
    "homepage": "http://www.everyeye.com",
    "weekday": "09:30 ~ 18:00",
    "saturday": "09:30 ~ 15:00",
    "holiday": "휴무",
    "remarks": "금요일 09:30 ~ 19:00",
    "photo": "노고산동_신촌연세안과의원_01.jpg,노고산동_신촌연세안과의원_02.jpg,노고산동_신촌연세안과의원_03.jpg,노고산동_신촌연세안과의원_04.jpg",
    "review": "진료가 매우 친절하고 실력이 좋다. 치료가 효과적이다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "안과",
    "address": "서강로 144 4층 4호 (노고산동)",
    "name": "이안과의원",
    "category": "의원",
    "tel": "02-715-2606",
    "zipcode": "04100",
    "homepage": "",
    "weekday": "09:30 ~ 18:00",
    "saturday": "09:30 ~ 12:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "노고산동_이안과의원_01.jpg,노고산동_이안과의원_02.jpg,노고산동_이안과의원_03.jpg",
    "review": "시설이 별로 좋지 않다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "대흥동",
    "subject": "안과",
    "address": "신촌로 174 2층 (대흥동, 중우빌딩)",
    "name": "오세오안과의원",
    "category": "의원",
    "tel": "02-703-1954",
    "zipcode": "04104",
    "homepage": "http://www.oseoi.com/",
    "weekday": "09:30 ~ 18:00",
    "saturday": "09:30 ~ 13:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00 목요일 14:00 ~ 18:00",
    "photo": "대흥동_오세오안과의원_01.jpg,대흥동_오세오안과의원_02.jpg,대흥동_오세오안과의원_03.jpg,대흥동_오세오안과의원_04.jpg",
    "review": "시설이 아주 깔끔하다. 고가의 장비들을 사용한다. 하지만 의사선생님이 조금 불친절하고 가격이 비싸다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "안과",
    "address": "신촌로 93 2층 (창천동)",
    "name": "빛사랑안과의원",
    "category": "의원",
    "tel": "02-323-5300",
    "zipcode": "03789",
    "homepage": "http://lasikindex.co.kr/",
    "weekday": "09:30 ~ 18:30",
    "saturday": "09:30 ~ 14:00",
    "holiday": "휴무",
    "remarks": "금요일 09:30 ~ 20:00",
    "photo": "창천동_빛사랑안과의원_01.jpg,창천동_빛사랑안과의원_02.jpg,창천동_빛사랑안과의원_03.jpg",
    "review": "실력도 좋고 친절하고 저렴하지만 대기시간이 길다. 라식,라섹 수술을 잘한다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "안과",
    "address": "신촌로 99 8층,9층 (창천동)",
    "name": "새빛안과의원",
    "category": "의원",
    "tel": "02-393-4200",
    "zipcode": "03779",
    "homepage": "",
    "weekday": "09:30 ~ 18:30",
    "saturday": "09:30 ~ 16:00",
    "holiday": "휴무",
    "remarks": "금요일 09:30 ~ 20:00",
    "photo": "",
    "review": "병원규모가 조금 커서 의사가 여러명이라 불친절한 의사도 있고 친절한 의사도 있다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "성형외과,피부과",
    "address": "신촌로 68 2층 (노고산동)",
    "name": "라마르의원",
    "category": "의원",
    "tel": "02-323-7710",
    "zipcode": "04057",
    "homepage": "http://www.newlamar.com/",
    "weekday": "11:00 ~ 21:00",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "수요일 13:00 ~ 20:00",
    "photo": "노고산동_라마르의원_01.jpg,노고산동_라마르의원_02.jpg,노고산동_라마르의원_03.jpg,노고산동_라마르의원_04.jpg,노고산동_라마르의원_05.jpg,노고산동_라마르의원_06.jpg",
    "review": "실력이 좋고 친절하지만 광고를 너무 많이하여 병원같지가 않게 느껴질 때가 있다. 코 필러를 잘한다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "피부과",
    "address": "신촌로 61 2,3층 (창천동)",
    "name": "라인앤뷰의원",
    "category": "의원",
    "tel": "02-1600-9833",
    "zipcode": "03787",
    "homepage": "http://linenview.com/",
    "weekday": "10:30~19:30",
    "saturday": "휴무",
    "holiday": "휴무",
    "remarks": "월요일 금요일 10:30 ~ 21:00",
    "photo": "창천동_라인앤뷰의원_01.jpg",
    "review": "눈썹 문신을 잘하고 남자들도 많이 간다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "성형외과,피부과",
    "address": "연세로 21 7층 (창천동)",
    "name": "봄눈첫잎술의원",
    "category": "의원",
    "tel": "02-6925-1215",
    "zipcode": "03789",
    "homepage": "http://springeye.co.kr",
    "weekday": "11:30 ~ 19:30",
    "saturday": "10:00 ~ 15:30",
    "holiday": "휴무",
    "remarks": "월/화 10:30 ~ 20:30 금 11:30 ~ 20:30",
    "photo": "창천동_봄눈첫잎술의원_01.jpg,창천동_봄눈첫잎술의원_02.jpg",
    "review": "입술필러, 입꼬리 교정 등을 전문적으로 하며 시설이 매우 고급스럽다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "피부과,성형외과",
    "address": "신촌로 73 6층 (창천동)",
    "name": "연세스타피부과의원",
    "category": "의원",
    "tel": "02-332-0023",
    "zipcode": "03789",
    "homepage": "http://www.starskin.co.kr",
    "weekday": "10:00 ~ 20:00",
    "saturday": "10:00 ~ 17:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "창천동_연세스타피부과의원_01.jpg,창천동_연세스타피부과의원_02.jpg,창천동_연세스타피부과의원_03.jpg,창천동_연세스타피부과의원_04.jpg",
    "review": "규모가 크다. 불친절한 의사도 있고 친절한 의사도 있다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "피부과",
    "address": "연세로 29 4층 (창천동)",
    "name": "오에스티의원",
    "category": "의원",
    "tel": "02-322-7570",
    "zipcode": "03788",
    "homepage": "http://www.ostclinic.co.kr",
    "weekday": "11:00 ~ 19:00",
    "saturday": "13:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "목요일 휴무 / 일요일 13:00 ~ 16:00",
    "photo": "창천동_오에스티의원_01.jpg,창천동_오에스티의원_02.jpg,창천동_오에스티의원_03.jpg",
    "review": "오픈한지 얼마 안됬고 다양한 진료를 한다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "내과,정형외과,신경외과,영상의학과,재활의학과,가정의학과",
    "address": "신촌로16길 4 2층 (노고산동)",
    "name": "성모재활의학과의원",
    "category": "의원",
    "tel": "02-3142-8275",
    "zipcode": "04057",
    "homepage": "",
    "weekday": "09:00 ~ 18:30",
    "saturday": "09:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "토요일 1,3째 주 휴진",
    "photo": "",
    "review": "물리 치료는 조금 불친절하고 의사는 친절하게 진료를 잘 봐준다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "정형외과",
    "address": "신촌로 68 3층 (노고산동)",
    "name": "연세수정형외과의원",
    "category": "의원",
    "tel": "02-332-1320",
    "zipcode": "04057",
    "homepage": "",
    "weekday": "09:00 ~ 19:00",
    "saturday": "09:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "",
    "review": "의사 선생님께서 나직하게 잘 설명해주신다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "대흥동",
    "subject": "외과,정형외과,신경외과",
    "address": "신촌로 162 3층 (대흥동)",
    "name": "위광민의원",
    "category": "의원",
    "tel": "02-701-3100",
    "zipcode": "04104",
    "homepage": "",
    "weekday": "09:00 ~ 18:00",
    "saturday": "09:00 ~ 13:00",
    "holiday": "09:00 ~ 13:00",
    "remarks": "",
    "photo": "대흥동_위광민의원_01.jpg,대흥동_위광민의원_02.jpg,대흥동_위광민의원_03.jpg",
    "review": "신촌주변에 몇 안되는 정형외과라서 사람들이 많이 몰린다.\n물리치료실은 사람이 많아서 불친절하고 의사선생님의 진료는 친절하다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "성형외과,가정의학과,피부과",
    "address": "신촌로 67 (창천동, 거촌빌딩 6층)",
    "name": "이에스의원",
    "category": "의원",
    "tel": "02-334-1400",
    "zipcode": "03787",
    "homepage": "http://www.esbeauty.kr/",
    "weekday": "10:00 ~ 19:00",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "월금 10~ 21\n수요일 14~21",
    "photo": "창천동_이에스의원_01.jpg,창천동_이에스의원_02.jpg,창천동_이에스의원_03.jpg",
    "review": "친절하고 시술 이벤트가 많다. 한가지 진료를 보는데 단계별로 관리를 해줘서 인기가 많다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "성형외과,피부과",
    "address": "신촌로 109 502호 (창천동, 르메이에르타운)",
    "name": "연세자연미성형외과의원",
    "category": "의원",
    "tel": "02-365-4553",
    "zipcode": "03779",
    "homepage": "http://1004clinic.com",
    "weekday": "09:00 ~ 18:00",
    "saturday": "09:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "수요일 금요일 09:00 ~ 20:00",
    "photo": "창천동_연세자연미성형외과의원_01.jpg,창천동_연세자연미성형외과의원_02.jpg,창천동_연세자연미성형외과의원_03.jpg,창천동_연세자연미성형외과의원_04.jpg,창천동_연세자연미성형외과의원_05.jpg",
    "review": "시설이 고급지고 깔끔하다. 의사선생님이 친절하시다"
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "성형외과,피부과",
    "address": "서강로 137 2층 201~202호 (노고산동, (주)HTC까사빌)",
    "name": "연세리즈의원",
    "category": "의원",
    "tel": "02-333-0207",
    "zipcode": "04058",
    "homepage": "http://www.ysleeds.co.kr/",
    "weekday": "10:00 ~ 20:00",
    "saturday": "10:00 ~ 17:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "노고산동_연세리즈의원_01.jpg,노고산동_연세리즈의원_02.jpg,노고산동_연세리즈의원_03.jpg,노고산동_연세리즈의원_04.jpg",
    "review": "시설이 좋고 깔끔하다. 적절한 가격에 좋은 장비로 좋은 시술을 해주지만 서비스적으로 조금 부족하다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "대현동",
    "subject": "성형외과",
    "address": "이화여대길 7 (대현동)",
    "name": "허은성형외과의원",
    "category": "의원",
    "tel": "02-313-6767",
    "zipcode": "03766",
    "homepage": "http://www.hureunps.net",
    "weekday": "10:00 ~ 18:00",
    "saturday": "10:00 ~ 15:00",
    "holiday": "휴무",
    "remarks": "",
    "photo": "대현동_허은성형외과의원_01.jpg,대현동_허은성형외과의원_02.jpg,대현동_허은성형외과의원_03.jpg,대현동_허은성형외과의원_04.jpg",
    "review": "눈 재수술을 잘한다고 알려져있다. 꼼꼼히 진료를 봐주신다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "대현동",
    "subject": "성형외과",
    "address": "신촌로 189 201호(대현동, 이화인비따례오피스텔)",
    "name": "아이미성형외과의원",
    "category": "의원",
    "tel": "02-363-2710",
    "zipcode": "",
    "homepage": "http://www.imiclinic.co.kr/",
    "weekday": "10:00 ~ 19:00",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00",
    "photo": "대현동_아이미성형외과의원_01.jpg,대현동_아이미성형외과의원_02.jpg,대현동_아이미성형외과의원_03.jpg,대현동_아이미성형외과의원_04.jpg",
    "review": "깔끔하고 시술 이벤트가 많다. 어머님들도 많이 이용하신다. 다양한 시술을 한다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "대흥동",
    "subject": "성형외과",
    "address": "신촌로 180 3층 (대흥동)",
    "name": "홍승현성형외과의원",
    "category": "의원",
    "tel": "02-706-0667",
    "zipcode": "04104",
    "homepage": "http://www.hshclinic.com/",
    "weekday": "10:00 ~ 18:30",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:00 ~ 14:00",
    "photo": "대흥동_홍승현성형외과의원_01.jpg,대흥동_홍승현성형외과의원_02.jpg,대흥동_홍승현성형외과의원_03.jpg,대흥동_홍승현성형외과의원_04.jpg",
    "review": "가격도 적당하고 꼼꼼하게 잘 설명해준다. 여의사가 친절하게 고민을 잘 들어준다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "대흥동",
    "subject": "성형외과",
    "address": "신촌로 174 4층 (대흥동, 중우빌딩)",
    "name": "윤정섭성형외과의원",
    "category": "의원",
    "tel": "02-717-3525",
    "zipcode": "04104",
    "homepage": "http://www.yoonbeauty.com/",
    "weekday": "10:00 ~ 18:00",
    "saturday": "10:00 ~ 14:00",
    "holiday": "휴무",
    "remarks": "목요일 휴무 수요일 13:00 ~ 20:30 \n점심시간 13:00 ~ 14:30",
    "photo": "대흥동_윤정섭성형외과의원_01.jpg",
    "review": "포근한 분위기, 원장의 경력이 24년이라 신뢰가 간다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "성형외과,피부과",
    "address": "신촌로 88 태영빌딩 3층 (노고산동)",
    "name": "엔비유의원",
    "category": "의원",
    "tel": "02-323-3993",
    "zipcode": "04058",
    "homepage": "http://www.nvu.co.kr/",
    "weekday": "10:00 ~ 19:30",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "수요일 13:00 ~ 21:00",
    "photo": "노고산동_엔비유의원_01.jpg,노고산동_엔비유의원_02.jpg,노고산동_엔비유의원_03.jpg,노고산동_엔비유의원_04.jpg,노고산동_엔비유의원_05.jpg,노고산동_엔비유의원_06.jpg,노고산동_엔비유의원_07.jpg,노고산동_엔비유의원_08.jpg",
    "review": "분위기가 고급지다. 지방 제거를 전문적으로 한다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "산부인과",
    "address": "신촌로 92 신촌카리스빌딩 8층 (노고산동)",
    "name": "신촌티오피산부인과의원",
    "category": "의원",
    "tel": "02-335-2228",
    "zipcode": "04058",
    "homepage": "topwoman.co.kr",
    "weekday": "10:00 ~ 20:00",
    "saturday": "10:00 ~ 20:00",
    "holiday": "10:00 ~ 20:00",
    "remarks": "",
    "photo": "노고산동_신촌티오피산부인과의원_01.jpg,노고산동_신촌티오피산부인과의원_02.jpg,노고산동_신촌티오피산부인과의원_03.jpg,노고산동_신촌티오피산부인과의원_04.jpg,노고산동_신촌티오피산부인과의원_05.jpg",
    "review": "여의사 진료, 365일 진료, 공휴일에도 진료를 하는 것이 가장 큰 장점이다"
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "노고산동",
    "subject": "산부인과",
    "address": "서강로 144 4층 5호 (노고산동)",
    "name": "이브산부인과의원",
    "category": "의원",
    "tel": "02-6368-2323",
    "zipcode": "04100",
    "homepage": "http://www.i-eve.kr",
    "weekday": "10:00 ~ 18:00",
    "saturday": "10:00 ~ 17:00",
    "holiday": "휴무",
    "remarks": "수요일 휴무 점심시간 13:30 ~ 14:30",
    "photo": "노고산동_이브산부인과의원_01.jpg,노고산동_이브산부인과의원_02.jpg,노고산동_이브산부인과의원_03.jpg",
    "review": "여의사 진료, 의사 선생님께서 정말 친절히 잘 설명해주신다. 만족도가 가장 높은 산부인과 중 하나이다."
  },
  {
    "city": "서울특별시",
    "district": "마포구",
    "neighborhood": "대흥동",
    "subject": "산부인과",
    "address": "백범로 91 2층 (대흥동)",
    "name": "윤의원",
    "category": "의원",
    "tel": "02-876-7878",
    "zipcode": "04111",
    "homepage": "http://www.yoonlabclinic.com/",
    "weekday": "09:30 ~ 20:00",
    "saturday": "09:30 ~ 15:00",
    "holiday": "휴무",
    "remarks": "화,수,금요일 18:30 진료마감",
    "photo": "대흥동_윤의원_01.jpg,대흥동_윤의원_02.jpg,대흥동_윤의원_03.jpg,대흥동_윤의원_04.jpg",
    "review": "여의사 진료, 시설이 매우 고급지고 전문적인 느낌을 강하게 받을 수 있다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "산부인과",
    "address": "신촌로 107 5층 (창천동)",
    "name": "그대안에산부인과의원",
    "category": "의원",
    "tel": "02-363-2400",
    "zipcode": "03779",
    "homepage": "http://sc.intouclinic.co.kr",
    "weekday": "10:00 ~ 20:00",
    "saturday": "10:00 ~ 16:00",
    "holiday": "휴무",
    "remarks": "점심시간 13:30 ~ 14:30",
    "photo": "창천동_그대안에산부인과의원_01.jpg,창천동_그대안에산부인과의원_02.jpg,창천동_그대안에산부인과의원_03.jpg,창천동_그대안에산부인과의원_04.jpg",
    "review": "여의사 진료, 가격이 비싼 만큼 좋다. 오픈한지 얼마 안되서 시설이 아주 좋고 의사, 간호사 모두 친절하다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "산부인과,피부과",
    "address": "연세로 12 (창천동, 피델리아빌딩 8층)",
    "name": "로앤산부인과의원",
    "category": "의원",
    "tel": "02-326-5000",
    "zipcode": "03779",
    "homepage": "http://www.tuu.kr/",
    "weekday": "10:00 ~ 21:00",
    "saturday": "10:00 ~ 18:00",
    "holiday": "휴무",
    "remarks": "공휴일 09:00 ~ 13:00",
    "photo": "창천동_로앤산부인과의원_01.jpg,창천동_로앤산부인과의원_02.jpg,창천동_로앤산부인과의원_03.jpg",
    "review": "여의사 진료, 시설은 좋으나 간호사, 의사 모두 불친절하다. 비용도 저렴하지는 않다."
  },
  {
    "city": "서울특별시",
    "district": "서대문구",
    "neighborhood": "창천동",
    "subject": "산부인과",
    "address": "신촌로 99 10층 (창천동)",
    "name": "애플산부인과의원",
    "category": "의원",
    "tel": "02-393-3060",
    "zipcode": "03779",
    "homepage": "http://applewoman.co.kr/sc",
    "weekday": "10:00 ~ 21:00",
    "saturday": "10:00 ~ 18:00",
    "holiday": "휴무",
    "remarks": "공휴일 10:00 ~ 16:00",
    "photo": "창천동_애플산부인과의원_01.jpg,창천동_애플산부인과의원_02.jpg,창천동_애플산부인과의원_03.jpg",
    "review": "여의사 진료, 친절하기는 하나 과잉 진료를 하는 느낌을 받는 사람이 종종 있다고 한다."
  }
];


var fs = require('fs');
 
for (var i = 0; i < processing_data.length; i++) {
   //One Object In Data
   thisObject = processing_data[i];

   //key를 통해 접근해서 ""이면 삭제.
   for(var key in thisObject){
      if(thisObject[key] === ""){

         delete thisObject[key]; 

      } 

      //photo, subject(array가 되어야할 필드) 중 데이터가 있었던 필드에 대해 array로 만드는 작업.
      if ((thisObject[key] !== undefined) && (key === "photo" || key == "subject")){
         
         thisObject[key] = thisObject[key].split(',')

      }

   }


}

var processed_data = JSON.stringify(processing_data);

fs.writeFile('processed_data.js', processed_data, 'utf8', function(err) {
   console.log('비동기적 파일 쓰기 완료');
});










